# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Jupiter\Documents\PSoC Creator\Object_Classifier\Object_Classifier.cydsn\Object_Classifier.cyprj
# Date: Wed, 04 Jan 2023 00:00:25 GMT
#set_units -time ns
create_clock -name {CapSense_ModClk(FFB)} -period 10625 -waveform {0 5312.5} [list [get_pins {ClockBlock/ff_div_3}]]
create_clock -name {EZI2C_SCBCLK(FFB)} -period 625 -waveform {0 312.5} [list [get_pins {ClockBlock/ff_div_0}]]
create_clock -name {Clock(FFB)} -period 2000 -waveform {0 1000} [list [get_pins {ClockBlock/ff_div_4}]]
create_clock -name {CyILO} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {CapSense_ModClk} -source [get_pins {ClockBlock/hfclk}] -edges {1 255 511} [list]
create_generated_clock -name {EZI2C_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 15 31} [list]
create_generated_clock -name {Clock} -source [get_pins {ClockBlock/hfclk}] -edges {1 49 97} [list]


# Component constraints for C:\Users\Jupiter\Documents\PSoC Creator\Object_Classifier\Object_Classifier.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Jupiter\Documents\PSoC Creator\Object_Classifier\Object_Classifier.cydsn\Object_Classifier.cyprj
# Date: Wed, 04 Jan 2023 00:00:23 GMT
